# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb3c8a031da5880323c5ac1b99fe7d04822fe641aff0529c9ef01b049e148fd1435e6a4c37680752dc02920a76c15781c5c4fd7f2b621df02abf0343eec5322

test:
  secret_key_base: c30bde9e7ca5790186b2ec109936bae18ec6165b83bbf571792cd15833af614d1228f554e74372bed95aa5c81cebf35c9a42871d47dc592a87f253a02e7107d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
